# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import common_pb2 as common__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in common_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MathesisServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetConcept = channel.unary_unary(
                '/mathesis.common.MathesisService/GetConcept',
                request_serializer=common__pb2.GetConceptRequest.SerializeToString,
                response_deserializer=common__pb2.Concept.FromString,
                _registered_method=True)
        self.ListConcepts = channel.unary_unary(
                '/mathesis.common.MathesisService/ListConcepts',
                request_serializer=common__pb2.ListConceptsRequest.SerializeToString,
                response_deserializer=common__pb2.ListConceptsResponse.FromString,
                _registered_method=True)
        self.GetQuestion = channel.unary_unary(
                '/mathesis.common.MathesisService/GetQuestion',
                request_serializer=common__pb2.GetQuestionRequest.SerializeToString,
                response_deserializer=common__pb2.Question.FromString,
                _registered_method=True)
        self.AnalyzeProblem = channel.unary_unary(
                '/mathesis.common.MathesisService/AnalyzeProblem',
                request_serializer=common__pb2.AnalyzeProblemRequest.SerializeToString,
                response_deserializer=common__pb2.AnalyzeProblemResponse.FromString,
                _registered_method=True)


class MathesisServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetConcept(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListConcepts(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetQuestion(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AnalyzeProblem(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MathesisServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetConcept': grpc.unary_unary_rpc_method_handler(
                    servicer.GetConcept,
                    request_deserializer=common__pb2.GetConceptRequest.FromString,
                    response_serializer=common__pb2.Concept.SerializeToString,
            ),
            'ListConcepts': grpc.unary_unary_rpc_method_handler(
                    servicer.ListConcepts,
                    request_deserializer=common__pb2.ListConceptsRequest.FromString,
                    response_serializer=common__pb2.ListConceptsResponse.SerializeToString,
            ),
            'GetQuestion': grpc.unary_unary_rpc_method_handler(
                    servicer.GetQuestion,
                    request_deserializer=common__pb2.GetQuestionRequest.FromString,
                    response_serializer=common__pb2.Question.SerializeToString,
            ),
            'AnalyzeProblem': grpc.unary_unary_rpc_method_handler(
                    servicer.AnalyzeProblem,
                    request_deserializer=common__pb2.AnalyzeProblemRequest.FromString,
                    response_serializer=common__pb2.AnalyzeProblemResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'mathesis.common.MathesisService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('mathesis.common.MathesisService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MathesisService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetConcept(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mathesis.common.MathesisService/GetConcept',
            common__pb2.GetConceptRequest.SerializeToString,
            common__pb2.Concept.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListConcepts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mathesis.common.MathesisService/ListConcepts',
            common__pb2.ListConceptsRequest.SerializeToString,
            common__pb2.ListConceptsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetQuestion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mathesis.common.MathesisService/GetQuestion',
            common__pb2.GetQuestionRequest.SerializeToString,
            common__pb2.Question.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AnalyzeProblem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mathesis.common.MathesisService/AnalyzeProblem',
            common__pb2.AnalyzeProblemRequest.SerializeToString,
            common__pb2.AnalyzeProblemResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
